# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'spotqueueRN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for spotqueueRN

  target 'spotqueueRN-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'spotqueueRNTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'spotqueueRN-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for spotqueueRN-tvOS

  target 'spotqueueRN-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
